
name: SimulaQron backend tests

on: push

jobs:
  examples:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install netqasm
      run: make install
    - name: Install simulaqron
      run: pip install simulaqron==4.0
    - name: Run examples
      env:
          NETQASM_SIMULATOR: simulaqron
      run: make external-examples
